### ISSUE TITLE
GRAPE does not work in 64-bit Windows

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/grape#10]
Please see https://github.com/gap-system/gap/issues/1523 where it was reported initially by @ignatsoroko.

**Comment by lhsoicher** [comment]
It looks to me like the 64-bit Windows distribution of of GAP should support the use of the Windows 32-bit dreadnautB.exe as detailed in the Edit (07/22/17): Temporary workaround of @ignatsoroko reported in  gap-system/gap#1523

**Comment by lhsoicher** [comment]
Hi Alex,

As I said in my comment on this on github, I believe this problem needs to be fixed in the 64-bit Windows distribution of GAP, not in GRAPE itself.

Best,
Leonard

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alex-konovalov** [comment]
Thanks @lhsoicher! I am not so sure yet - will investigate.
