### ISSUE TITLE
Iconsistent use of automorphism groups for search of cliques

### ISSUE THREAD

**Issue by TJenrich** [gap-packages/grape#18]
Suppose that one wants to check the hypothesis that the graph gamma does not contain a clique of size s. For the current version of GRAPE,  it can be (much) faster to call 
`CliqueNumber(gamma);`
instead of the more basic 
`CompleteSubgraphsOfGivenSize(gamma,s+1,0);`
That seems to be inplausible because CliqueNumber(gamma) is implemented as Length(MaximumClique(gamma)), and (for not too simple cases)  MaximumClique performs an iteration, typically calling 
CompleteSubgraphsOfGivenSize multiple times. 
The reason is that MaximumClique does this

`G:=AutomorphismGroup(gamma); 
if G=gamma.group then 
   delta:=gamma;
else
  delta:=NewGroupGraph(G,gamma); # to take full advantage of Aut(gamma)
fi;`

and calls CompleteSubgraphsOfGivenSize(delta,...) in the following iteration. If the automorphism group G is not trivial, the calculation can be much faster. Otherwise, time has been wasted for the calculation of the automorphism group. So, depending on the graph, the user could want to include or to exclude the calculation of the automorphism group for  use in CompleteSubgraphsOfGivenSize, not depending on whether it is could directly or (as in the case of CliqueNumber) indirectly.

**Comment by TJenrich** [comment]
Correction (in the last sentence):   ... whether it is called ...

**Comment by TJenrich** [comment]
Correction (sorry): 
`CompleteSubgraphsOfGivenSize(gamma,s,0);`

**Comment by lhsoicher** [comment]
This "inconsistency" is deliberate.

My usual policy is to let the user decide whether and when to calculate the automorphism group A of a graph gamma, and whether to set `gamma:=NewGroupGraph(A,gamma);`  to associate A with gamma. However, for the high-level function MaximumClique, which may call CompleteSubgraphsOfGivenSize repeatedly, I made the decision to calculate and make use of the automorphism group of the input graph automatically (for the general case), but not, of course, to change the group associated to the user's input graph. 

It is worth pointing out that CompleteSubgraphsOfGivenSize applied to a (simple) graph gamma is always meant to work using the given group, `gamma.group`, associated to gamma. The documentation makes the role of `gamma.group` clear when classifying cliques or when dealing with a vertex-weighted graph, but I should probably make more clear in the documentation the consequence of using `gamma.group` in the case of determining the existence of a single clique of size s in a graph gamma without vertex weights, and that the user may first wish to calculate the automorphism group of gamma and to associate that group with gamma before proceeding in this case.

**Comment by TJenrich** [comment]
Thank you @lhsoicher for your detailed answer.
