### ISSUE TITLE
Why does grape version 4.8.5 demand GAP version 4.11?

### ISSUE THREAD

**Issue by TJenrich** [gap-packages/grape#28]
First, thanks for following (some of) my proposals with respect to the interaction with dreadnaut.
But now: While version 4.8.3 worked fine with GAP version 4.10.2, version 4.8.5 demands the GAP version to be at least 4.11  . On my system (Lubuntu 20.4) GAP version 4.10.2 is not just the currently installed one but also the most recent one that is provided via the package manager Muon. I tried to switch to version 4.11 manually earlier but did not succeed. I do not want to install a new version of Lubuntu just to have (perhaps) a more recent version of GAP in the packages.
On the other hand, changing the required version in PackageInfo.g is easy and seems to have no drawback. At least, testall.g runs through without any error message.  
So, why is GAP version 4.11 required, and which drawbacks are to expect when running GRAPE version 4.8.5 on GAP version 4.10.2  ?

**Comment by lhsoicher** [comment]
Thanks @TJenrich for your suggestions that I incorporated in GRAPE 4.8.4 and GRAPE 4.8.5. Although I know of no problem using GRAPE 4.8.5 with GAP 4.10.2, my most extensive testing of GRAPE 4.8.5 has been using GAP 4.11.0 and GAP 4.11.1. In addition, I wanted users to upgrade their version of GAP if they have an old one and they want to run a new version of GRAPE. Please feel free to change the minimum required version of GAP in your GRAPE 4.8.5 PackageInfo.g file to 4.10.2, but please let me know of any problems.

**Comment by TJenrich** [comment]
Thank you, @lhsoicher, for your quick answer. Good news that you do not expect problems when GRAPE 4.8.5 runs on GAP 4.10.2. 
But in that case I do not understand the motive behind 
"I wanted users to upgrade their version of GAP if they have an old one and they want to run a new version of GRAPE" 
because upgrading GAP could be difficult not just for me. Modifying PackageInfo.g, on the other hand, is at least an inconvinience and some users could hesitate to do it.

**Comment by lhsoicher** [comment]
Thank you @TJenrich for this feedback. The motive is that users should be using a recent version of GAP, with any new improvements and bug-fixes, on which the latest version of GRAPE has been most extensively tested. I would recommend downloading the latest official release of GAP for Linux from https://www.gap-system.org and installing it, say within your home directory, for a single user. This should not be difficult.
