### ISSUE TITLE
Large Cayley Graphs

### ISSUE THREAD

**Issue by nakareme** [gap-packages/grape#33]
Would you please help me about the following issue:
I need to calculate the diameter of CyleyGraph of a direct product of a finite group. For example, if G is alternating group A5  with 60 elements the Cayley Graph of GxGxG has 216 000 vertices. I tried to use GAP for finding the diameter in this case but it seems that the number of vertices is two big. What is the maximum size of graphs that we can create by Grape?

**Comment by lhsoicher** [comment]
The largest possible number of vertices of a graph you can create using GRAPE depends on the vertex-degrees of the graph, how you construct the graph, in particular, how you make use of graph symmetry, as well as how much RAM you have on your computer.  However, a Cayley graph for A_5xA_5xA_5 should not be a problem. I append an example computation, which takes about 4 seconds on my i5 laptop. Please see the documentation for the function CayleyGraph in GRAPE.

gap> LoadPackage("grape");
─────────────────────────────────────────────────────────────────────────────
Loading  GRAPE 4.8.5 (GRaph Algorithms using PErmutation groups)
by Leonard H. Soicher (http://www.maths.qmul.ac.uk/~lsoicher/).
Homepage: https://gap-packages.github.io/grape
Report issues at https://github.com/gap-packages/grape/issues
─────────────────────────────────────────────────────────────────────────────
true
gap> A:=AlternatingGroup([1..5]);
Alt( [ 1 .. 5 ] )
gap> G:=DirectProduct(A,A,A);;
gap> gens:=GeneratorsOfGroup(G);
[ (1,2,3,4,5), (3,4,5), (6,7,8,9,10), (8,9,10), (11,12,13,14,15), (13,14,15) ]
gap> C:=CayleyGraph(G,gens,true);; # for example
gap> OrderGraph(C);
216000
gap> VertexDegrees(C);
[ 12 ]
gap> Diameter(C);
18
gap> Girth(C);
3
gap> quit;

**Comment by lhsoicher** [comment]
I suggest you download the latest version of GAP (version 4.12.0) from https://www.gap-system.org/Releases/4.12.0.html
This will include the latest version of GRAPE (and many other packages). Follow the instructions for Linux and OS X, including how to build most of the packages, which will include building GRAPE.

**Comment by nakareme** [comment]
Hi, thank you for your answer. I dit it and now is working well. I wrote a code for calculating the diameter of Cayley graph of direct power A5xA5, respect to the all generating sets of size 2.  It is more than 20 hours that is running and dose not  finish. Can you help me?
