### ISSUE TITLE
Please provide a tarball without nauty22

### ISSUE THREAD

**Issue by StefanBruens** [gap-packages/grape#34]
The license of nauty prior to 2.6 is problematic, as it disallow commercial use.

Providing and building nauty separately, like it is already done for bliss, is the much cleaner solution.

This also avoids the somewhat confusing license situation of the repository and created tarballs: although the grape license is GPL-2.0-or-later, the complete distribution also falls under the nauty license. As nauty/dreadnutB is only called as a separate binary and thus is an "mere aggregation" this is fine here, but the situation is still somewhat confusing on a first glimpse.

**Comment by lhsoicher** [comment]
The plan is to remove nauty 2.2 and  to include instead nauty & traces version 2.7r4 in the next version of GRAPE.

**Comment by StefanBruens** [comment]
I can see neither a release where this has happened, nor any changes in the repository ...
Why is this closed?

**Comment by lhsoicher** [comment]
I'm happy to keep this open until the new release actually happens.

**Comment by fingolfin** [comment]
@lhsoicher if you need any kind of help with that (e.g. regarding use of ReleaseTools, or just for testing, let me know)

**Comment by lhsoicher** [comment]
Thank you Max. I shall be preparing a new release of GRAPE over the next two weeks or so, which should include nauty 2.7r4. I'll let you know if I need any help.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by lhsoicher** [comment]
@fingolfin As you can see, commit 4faa7e59af0645a8d91a4ce47015a6b5368f80f7 has nauty 2.7r4 included in GRAPE, but fails on testing on CYGWIN. Can you tell what the problem is? Note that the executable to be made is now dreadnaut, rather than dreadnautB, if that helps. Thank you.

**Comment by fingolfin** [comment]
@lhsoicher will have a look, though @ChrisJefferson knows much more about Cygwin :-)

**Comment by fingolfin** [comment]
Oh I see, grape still uses AppVeyor for the Cygwin tests, not the new GitHub Actions based tests created by @wilfwilson. I'll try to see if I can make a pull request switching things over.

**Comment by lhsoicher** [comment]
GRAPE 4.9.0 is now released, and comes with nauty 2.8.6 instead of nauty 2.2.
