### ISSUE TITLE
 Utilizing the minimal cycles in Cayley graph to identify the power product expression of group elements equal to identity element of the group.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/grape#35]
Hi here,

I want to find the power product expression of group elements equal to identity element of the group. For this purpose, Dima Pasechnik (<dima@pasechnik.info>) gives me [the following idea](https://lists.uni-kl.de/gap/arc/forum/2022-11/msg00011.html):

> consider the Cayley graph of the group, w.r.t. the generators you want.
> Now, the minimal cycles in the graph are exactly the minimal, indecomposable,
> words in generators (i.e. power product experssions) you want.

Based on the above comment, I tried the following method but still can't figure out how to do the trick with the help of [grape](https://github.com/gap-packages/grape) package:

```gap
gap> LoadPackage("grape");
true
gap> C:=CayleyGraph(SymmetricGroup(4),[(1,2),(2,3),(3,4)]);
rec( adjacencies := [ [ 2, 3, 7 ] ], group := Group([
(1,10,17,19)(2,9,18,20)(3,12,14,21)(4,11,13,22)(5,7,16,23)(6,8,15,24),
(1,7)(2,8)(3,9)(4,10)(5,11)(6,12)(13,15)
      (14,16)(17,18)(19,21)(20,22)(23,24) ]), isGraph := true,
isSimple := true, names := [ (), (3,4), (2,3), (2,3,4), (2,4,3),
(2,4), (1,2), (1,2)(3,4), (1,2,3),
      (1,2,3,4), (1,2,4,3), (1,2,4), (1,3,2), (1,3,4,2), (1,3),
(1,3,4), (1,3)(2,4), (1,3,2,4), (1,4,3,2), (1,4,2), (1,4,3), (1,4),
(1,4,2,3), (1,4)(2,3) ],
  order := 24, representatives := [ 1 ], schreierVector := [ -1, 1, 1,
2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2 ] )
gap> Girth(C);
4
gap> Diameter(C);
6
```
Any tips will be appreciated.

Regards,
Zhao

**Comment by lhsoicher** [comment]
Are you looking for a list of defining relators for your group 
with respect to a given list of generators? If so, then you should proceed 
as follows in GAP (not using GRAPE):

gap> G:=SymmetricGroup(4);
Sym( [ 1 .. 4 ] )
gap> gens:=[(1,2),(2,3),(3,4)];
[ (1,2), (2,3), (3,4) ]
gap> iso:=IsomorphismFpGroupByGenerators(G,gens);
[ (1,2), (2,3), (3,4) ] -> [ F1, F2, F3 ]
gap> RelatorsOfFpGroup(Image(iso));
[ F2^2, F1^2, F3^2, (F3*F1)^2, (F3*F2)^3, (F1*F2)^3 ]
gap> 

See the GAP documentation for more info.

Best,
Leonard

________________________________________
From: hongyi-zhao ***@***.***>
Sent: 11 November 2022 08:18
To: gap-packages/grape
Cc: Subscribed
Subject: [gap-packages/grape]  Utilizing the minimal cycles in Cayley graph to identify the power product expression of group elements equal to identity element of the group. (Issue #35)

Hi here,

I want to find the power product expression of group elements equal to identity element of the group. For this purpose, Dima Pasechnik ***@***.******@***.***>) gives me the following idea<https://lists.uni-kl.de/gap/arc/forum/2022-11/msg00011.html>:

consider the Cayley graph of the group, w.r.t. the generators you want.
Now, the minimal cycles in the graph are exactly the minimal, indecomposable,
words in generators (i.e. power product experssions) you want.

Based on the above comment, I tried the following method but still can't figure out how to do the trick with the help of grape<https://github.com/gap-packages/grape> package:

gap> LoadPackage("grape");
true
gap> C:=CayleyGraph(SymmetricGroup(4),[(1,2),(2,3),(3,4)]);
rec( adjacencies := [ [ 2, 3, 7 ] ], group := Group([
(1,10,17,19)(2,9,18,20)(3,12,14,21)(4,11,13,22)(5,7,16,23)(6,8,15,24),
(1,7)(2,8)(3,9)(4,10)(5,11)(6,12)(13,15)
      (14,16)(17,18)(19,21)(20,22)(23,24) ]), isGraph := true,
isSimple := true, names := [ (), (3,4), (2,3), (2,3,4), (2,4,3),
(2,4), (1,2), (1,2)(3,4), (1,2,3),
      (1,2,3,4), (1,2,4,3), (1,2,4), (1,3,2), (1,3,4,2), (1,3),
(1,3,4), (1,3)(2,4), (1,3,2,4), (1,4,3,2), (1,4,2), (1,4,3), (1,4),
(1,4,2,3), (1,4)(2,3) ],
  order := 24, representatives := [ 1 ], schreierVector := [ -1, 1, 1,
2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2 ] )
gap> Girth(C);
4
gap> Diameter(C);
6

Any tips will be appreciated.

Regards,
Zhao

**Comment by hongyi-zhao** [comment]
Exactly. Thank you for pointing this out.
