### ISSUE TITLE
Almost there!

### ISSUE THREAD

**Issue by lhsoicher** [gap-packages/grape#41]
Thanks to @fingolfin and @ChrisJefferson , there is now only one check unsuccessful for c1ae51cf0f0b4964810a39a6e6bac8dbc07eb310

continuous-integration/appveyor/branch — AppVeyor build 

Is this easy to fix?

**Comment by fingolfin** [comment]
I fixed it by disabling AppVeyor for this repository (and indeed removing the last traces of it from the `gap-packages` organization).

I've also submitted two new PRs and updated my existing license PR. Please have a look at consider merging.

I'll have a look at the rest of grape now and give it a try on my compute next

**Comment by lhsoicher** [comment]
All checks now pass. Many thanks @fingolfin.
