### ISSUE TITLE
Try to obtain the MinimalGeneratingSet of an FP group with the clues of the relationship analysis among the relators based on graph theory.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/grape#45]
Hi here,

I try to obtain the MinimalGeneratingSet of an FP group with the clues of the relationship analysis among the relators based on graph theory. I wonder if the idea is feasible?

Here is an example:

```gap
gap> hom:=IsomorphismFpGroup(SpaceGroupOnLeftIT(3,229));;
gap> Image(IsomorphismSimplifiedFpGroup( Image(hom)));
<fp group on the generators [ f1, f2, f3, f6 ]>
gap> RelatorsOfFpGroup(last);
[ f1^2, f3^3, (f1*f2^-1)^2, f2^4, (f3*f2)^2, f6^-1*f3^-1*f6*f3, f6^-1*f2*f1*f6*f2*f1, (f1*f3^-1*f2)^2, f2*f6^-1*(f1*f6)^2*f2^-1*f6^-1, (f2^-1*f6^-1*f2^-1*f6)^2, 
  f3^-1*f2^-2*f6*f2*f3^-1*f2^-1*f1*f6*f1 ]
```
Is it possible to do some feasible analysis on the road of determining the MinimalGeneratingSet of this FP group with the help of grape package? 

Regards,
Zhao

**Comment by fingolfin** [comment]
I don't think so. 


But it's not hard to do this anywhere. Don't use fp groups for this, use a pcp group, they are much better behaved. You can use the abelian invariants to get a lower bound on the rank of the group (turns out to be 3 here) and then use `SmallGeneratingSet` to get, well, a small generating set. It's not hard to guess a minimal generating set from there:
```
gap> H:=Image(IsomorphismPcpGroup(G));
Pcp-group with orders [ 2, 2, 3, 2, 2, 0, 0, 0 ]
gap> AbelianInvariants(H);
[ 2, 2, 2 ]
gap> SmallGeneratingSet(H);
[ g1, g2, g3, g6 ]
gap> Index(H,Subgroup(H, [H.1, H.2, H.3, H.6]));
1
gap> Index(H,Subgroup(H, [H.1, H.2, H.3*H.6]));
1
```
So the elements H.1, H.2, H.3*H.6 (resp. their preimages under the isomorphism) form a minimal generating set.

**Comment by hongyi-zhao** [comment]
But I think you should enumerate all the combinations of [H.1, H.2, H.3, H.6] and then construct the possible products to do the test.

**Comment by fingolfin** [comment]
There is no need to enumerate all. You only neee one and thus can end the search once you found one.

besides, the group might also not be 3-generated, the you find nothing.

in practice I'd think long and hatd whether I really need a *minimal* generating set -- often a small one is sufficient

**Comment by hongyi-zhao** [comment]
I tried with the `SpaceGroupOnLeftIT(3, 171)` and even with a thorough enumeration, the result is still wrong:

```gap
AugmentedMatrixOnLeft := function( m, b )
  local d, g;

  d:= Unique(DimensionsMat(m));
  if Size(d) <> 1 then
    Error( "The matrix is not square." );
  fi;
  d := d[1];
  g:=List([1..d], x-> Concatenation( m[x], [b[x]]));
  # 0*[1..d]=Zero([1..d]);
  Add(g, Concatenation( Zero([1..d]), [1] ) ); 
  return g;
end;

MinimalGeneratingSetofPcpGroup:= function( gens )
  local d, tgens, G, iso, H, b, sgs, tupsps, minsgs;
  
  # The correct result should be 2.
  # gens:=GeneratorsOfGroup( SpaceGroupOnLeftIT(3,171));

  d := DimensionOfMatrixGroup( Group(gens) ) - 1;
  tgens:= List( IdentityMat(d) ,x -> AugmentedMatrixOnLeft( IdentityMat(d), x ) ); 
  gens := Union( gens, tgens );

  G := AffineCrystGroupOnLeft(gens);

  iso:=IsomorphismPcpGroup(G);
  H:=Image(iso);
  b:=Size(AbelianInvariants(H));
  sgs:=SmallGeneratingSet(H);
  if Length( sgs ) > b then
    # https://stackoverflow.com/questions/72302100/seeking-the-minimal-generating-set-of-a-affinecrystgroup
    tupsps:=List( [1..Length( sgs )], s -> List( Filtered(Tuples(sgs, s), x -> not ( Size(Unique(x) ) =1 or IsOne(Product(x) ) ) ), x -> Union(Difference(sgs, x), [Product(x)]) ) );
    tupsps:=Union(Filtered(tupsps, x -> not IsEmpty(x)));

    minsgs:=Filtered( tupsps, x -> Size(x) >= b);
    minsgs:=Filtered( minsgs, x -> Index(H,Subgroup(H, x)) =1 );
    minsgs:=Filtered( minsgs, x -> not IsEmpty(x));
    minsgs:=Filtered( minsgs, x -> Size(x) = Minimum(List(minsgs, x -> Size(x))) );
    if not IsEmpty(minsgs) then
      minsgs:=minsgs[1];
    fi;
  else
    minsgs:=sgs;
    # List(sgs, x -> PreImagesRepresentative(iso, x));
  fi;

  return minsgs;
end;
```
Then I got the following result:
```
gap> MinimalGeneratingSetofPcpGroup( GeneratorsOfGroup( SpaceGroupOnLeftIT(3, 171)) );
[ g1^2*g2, g3, g5 ]
``` 
In fact, the correct size should be 2.  So, I'm still confused. What's the cause of the problem?

Regards,
Zhao

**Comment by fingolfin** [comment]
Computing minimal generating sets of infinite non-nilpotent polycyclic is in general a very hard problem, so don't expect some magic to happen here. Nor can you expect to just write down an algorithm.

But you can at least experiment a bit, and my point just was that a good starting point is to first work out a generating set for the maximal abelian quotient G/G', lift it to G, and then try to "tweak" it until you get something that works.

So first we start with generators for G/G':
```
gap> G:=SpaceGroupOnLeftIT(3, 171);
SpaceGroupOnLeftIT(3,171,'1')
gap> H:=Image(IsomorphismPcpGroup(G));
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
gap> AbelianInvariants(H);
[ 0, 2 ]
gap> epi:=MaximalAbelianQuotient(H);
[ g1, g2, g5, g3, g4 ] -> [ g1, g2, g3, id, id ]
gap> MinimalGeneratingSet(Image(epi));
[ g1, g1*g2*g3 ]
gap> gens:=List(last, x -> PreImagesRepresentative(epi,x));
[ g1, g1*g2*g5 ]
```
Unfortunately the group these generate is too small:
```
gap> K:=Subgroup(H,gens);
Pcp-group with orders [ 2, 3, 0 ]
gap> Index(H,K);
infinity
gap> Pcp(K);
Pcp [ g1, g2, g5 ] with orders [ 2, 3, 0 ]
```

Now we can play around a bit  to find something (one could write a program to "try a bit" of course, but don't expect it to terminate in general):
```
gap> K:=Subgroup(H, [H.1*H.3, H.2]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
12
Pcp [ g1*g4, g2, g3*g4^2, g4^3, g5^4 ] with orders [ 2, 3, 0, 0, 0 ]
gap> K:=Subgroup(H, [H.1, H.2]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0 ]
infinity
Pcp [ g1, g2, g5^4 ] with orders [ 2, 3, 0 ]
gap> K:=Subgroup(H, [H.1*H.3, H.2]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
12
Pcp [ g1*g4, g2, g3*g4^2, g4^3, g5^4 ] with orders [ 2, 3, 0, 0, 0 ]
gap> K:=Subgroup(H, [H.1*H.3, H.2*H.4]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
28
Pcp [ g1*g4^4, g2*g4, g3*g4^3, g4^7, g5^4 ] with orders [ 2, 3, 0, 0, 0 ]
gap> K:=Subgroup(H, [H.1*H.3, H.2*H.5]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
3
Pcp [ g1*g4, g2, g3*g4^2, g4^3, g5 ] with orders [ 2, 3, 0, 0, 0 ]
gap> K:=Subgroup(H, [H.1*H.4, H.2*H.5]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
3
Pcp [ g1*g4, g2, g3*g4^2, g4^3, g5 ] with orders [ 2, 3, 0, 0, 0 ]
gap> K:=Subgroup(H, [H.1*H.4, H.2]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
12
Pcp [ g1*g4, g2, g3*g4^2, g4^3, g5^4 ] with orders [ 2, 3, 0, 0, 0 ]
gap> K:=Subgroup(H, [H.1*H.4, H.2*H.4]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
4
Pcp [ g1, g2, g3, g4, g5^4 ] with orders [ 2, 3, 0, 0, 0 ]
gap> K:=Subgroup(H, [H.1*H.4, H.2*H.4*H.5]); Index(H,K); Pcp(K);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
1
Pcp [ g1, g2, g3, g4, g5 ] with orders [ 2, 3, 0, 0, 0 ]
```

**Comment by hongyi-zhao** [comment]
> Computing minimal generating sets of infinite non-nilpotent polycyclic is in general a very hard problem, so don't expect some magic to happen here. Nor can you expect to just write down an algorithm.

> Now we can play around a bit to find something (one could write a program to "try a bit" of course, but don't expect it to terminate in general):

This is also my puzzle: if so, how the systematic results given in [the following documentation](https://www.researchgate.net/profile/Eric-Lord-2/post/Can-anybody-help-me-to-elaborate-the-concept-of-wyckoff-positions-in-crystallography/attachment/5ad49c984cde260d15d910fe/AS:616019777318913@1523881968758/download/spcgps.pdf) were obtained (although some of them are wrong).

[spcgps.pdf](https://github.com/gap-packages/grape/files/10201854/spcgps.pdf)
it to terminate in general)

**Comment by fingolfin** [comment]
In this example it ia enough to try these combinations. In general it is not. If this was an undergrad class where I teach this, I would now give the exercise to find a counterexample.

**Comment by hongyi-zhao** [comment]
> In this example it is enough to try these combinations.

I guess, for all pcp groups isomorphic to space groups, it is enough to try these combinations. Am I right?

> In general it is not. If this was an undergrad class where I teach this, I would now give the exercise to find a counterexample.

1. In general, do you mean we should try the unique combinations of the origin generators (with the size 1 to the length of these generators), and the products of **all the possible powers** of each element of all the unique tuples of these generators?
2. My group theory may not be as good as an undergraduate of a mathematics major. Could you please give me the exercise to find a counterexample?

**Comment by hongyi-zhao** [comment]
https://github.com/gap-packages/grape/issues/45#issuecomment-1345264858
> Computing minimal generating sets of infinite non-nilpotent polycyclic is in general a very hard problem, so don't expect some magic to happen here. Nor can you expect to just write down an algorithm.

See the following example:

```gap
gap> SG4d4565:=SpaceGroup(4, 4565);
SpaceGroupOnRightBBNWZ( 4, 31, 3, 1, 1 )
gap> IsSolvable(SG4d4565);
false
gap> not IsFinite(SG4d4565) and not IsNilpotent(SG4d4565);
#I  LowerCentralSeriesOfGroup: may not stop for infinite group <G>
true
gap> IsomorphismPcpGroup(SG4d4565);
fail
```
In this case, the pcp isomorphism cannot be obtained at all, so how do I use the technique you suggest here?
