### ISSUE TITLE
New test failure for GRAPE_ExactSetCover

### ISSUE THREAD

**Issue by orlitzky** [gap-packages/grape#48]
I updated our grape package from v4.9.0 to v4.9.2 today and our automated testing turned up one failure. The original report is at https://bugs.gentoo.org/944744 but I've tried to clean it up a bit below:

```
 ┌───────┐   GAP 4.13.1 of 2024-06-11
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: amd64
 Configuration:  gmp 6.3.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.7, PrimGrp 3.4.4, SmallGrp 1.5.4, TransGrp 3.6.5
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
─────────────────────────────────────────────────────────────────────────────
Loading GRAPE 4.9.2 (GRaph Algorithms using PErmutation groups)
by Leonard H. Soicher (https://webspace.maths.qmul.ac.uk/l.h.soicher/).
Homepage: https://gap-packages.github.io/grape
Report issues at https://github.com/gap-packages/grape/issues
─────────────────────────────────────────────────────────────────────────────
Architecture: amd64

testing: /var/tmp/portage/dev-gap/grape-4.9.2/temp/pkg/grape-4.9.2/tst/testall.tst
########> Diff in /var/tmp/portage/dev-gap/grape-4.9.2/temp/pkg/grape-4.9.2/tst/testall.tst:479
# Input is:
partition:=GRAPE_ExactSetCover(G,blocks,n,H);;
# Expected output:
# But found:
#E  SET_FILT_LIST[immutable homogeneous non-strictly-sorted plain list][0]
Error, Action not well-defined. See the manual section
``Action on canonical representatives''.
########
```

(There's another failure after that, but it's a consequence of the first one.)

The list of related packages that are installed:

* sci-mathematics/pari-2.15.5
*  sci-mathematics/cliquer-1.22
*  sci-mathematics/nauty-2.8.8-r1
*  sci-mathematics/gap-4.13.1-r1
*  dev-gap/transgrp-3.6.5
*  dev-gap/gapdoc-1.6.7
*  dev-gap/smallgrp-1.5.4
*  dev-gap/primgrp-3.4.4
*  dev-gap/crisp-1.4.6
*  dev-gap/fga-1.5.0
*  dev-gap/factint-1.6.3
*  dev-gap/irredsol-1.4.4
*  dev-gap/autpgrp-1.11
*  dev-gap/sophus-1.27
*  dev-gap/laguna-3.9.7
*  dev-gap/polycyclic-2.16
*  dev-gap/alnuth-3.2.1
*  dev-gap/radiroot-2.9
*  dev-gap/polenta-1.3.10
*  dev-gap/io-4.9.1
*  dev-gap/autodoc-2022.10.20
*  dev-gap/utils-0.87
*  dev-gap/resclasses-4.7.3
*  dev-gap/atlasrep-2.1.8
*  dev-gap/ctbllib-1.3.9
*  dev-gap/tomlib-1.2.11

**Comment by lhsoicher** [comment]
Thank you @orlitzky for this report. Although this problem does not show up for me when running GRAPE 4.9.2 in GAP 4.13.1 on my old i5 Ubuntu laptop, it is likely related to a problem I previously had with the development version of GAP, concerning "HashKeyBag as a hash function for lists" according to @hulpke. I believe this problem is now fixed in the development version of GAP, as is (hopefully) a related problem in GAP 4.13.1 concerning large orbits on sets. Please confirm and comment @fingolfin and @hulpke. Thanks.

**Comment by orlitzky** [comment]
We should already have the patch for that issue, unless I missed part of it? https://github.com/gentoo/gentoo/blob/master/sci-mathematics/gap/files/gap-4.13.1-hash-fixes.patch

**Comment by orlitzky** [comment]
It looks like we may need the more recent https://github.com/gap-system/gap/commit/19484a75098d43e75e3facfdd05dccefc358e43f as well. I'll give it a try.

**Comment by orlitzky** [comment]
It looks like that did the trick. We should be OK until 4.14.0 now, thanks!
