### ISSUE TITLE
Warning of unbound global variable

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/grape#8]
I install Grape v4.8.1 with `PackageMan` today, using today's GAP `stable-4.10` (eef7f9931295b2503efa90001724ca350ead27d3), I get the following error on loading Grape:

~~~~
Syntax warning: Unbound global variable in /Users/jdm/.gap/pkg/grape-4.8.1/lib\
/grape.g:3963
      newdelta:=InducedSubgraph(delta,A,Stabiliser(delta.group,c,OnSets));
~~~~

I only get this error if I "autoload" Grape, not if I do `LoadPackage("grape");`, maybe this is an issue with my setup rather than Grape, but I thought I'd report it anyway.

**Comment by lhsoicher** [comment]
Hi James,

This is known (see  https://github.com/gap-system/gap/issues/2996 ), 
and the problem will disappear with the next release of GRAPE,
in which "Stabiliser" is replaced by "Stabilizer".

Best,
Leonard 

________________________________________

**Comment by james-d-mitchell** [comment]
Thanks Leonard, I thought it might be something like that!

**Comment by wilfwilson** [comment]
Note @james-d-mitchell that this is also no longer a problem in GAP's `master` branch (via my PR https://github.com/gap-system/gap/pull/3010) and hence in the future GAP 4.11 and later.
